### ISSUE TITLE
Navigation Menu is cut-off or cropped

### ISSUE THREAD

**Issue by jahirfiquitiva** [radix-ui/website#499] opened 2022-10-19 00:36 UTC
### Current Behavior

When the menu is hovered or clicked for the first time, it will be cropped

![Shot 2022-10-18 at 19 34 39](https://user-images.githubusercontent.com/10360816/196570145-aeb62f8f-b022-4379-bd20-6ce64b945119.gif)

### Expected behavior

All the content should be completely visible every time one hovers or clicks on the menu

### Reproducible example

[Navigation Menu Docs](https://www.radix-ui.com/docs/primitives/components/navigation-menu)

**Comment by benoitgrelard** [comment] 2022-10-19 07:19
@andy-hook I transferred this to the website repo as I suppose it's an issue with this particularly styling/animation rather than with the primitive itself. Let me know if it's not.

**Comment by andy-hook** [comment] 2022-10-19 08:25
> I suppose it's an issue with this particularly styling/animation rather than with the primitive itself

We actually query the active content for the viewport size so if there's an issue it's likely internal.

@jahirfiquitiva I can't reproduce this, which browser are you using? are there any other specific steps you've taken to see this behaviour?

**Comment by benoitgrelard** [comment] 2022-10-19 08:35
Ah ok feel free to re-transfer if it turns out to be a real issue 👍

**Comment by jahirfiquitiva** [comment] 2022-10-19 14:17
@andy-hook I was using Edge on MacOS

**Comment by andy-hook** [comment] 2022-10-19 14:24
@jahirfiquitiva do you experience this in any other browser? would you mind posting your edge version, are you running an intel mac or apple chip? I've just tested in edge on window and macOS and still can't reproduce this issue 🤔

**Comment by jahirfiquitiva** [comment] 2022-10-19 15:38
@andy-hook Edge v `106.0.1370.47`, macOS v `12.6 (21G115)`, MacBook Pro 14 inch with M1 Pro

**Comment by andy-hook** [comment] 2022-10-20 10:12
> Edge v 106.0.1370.47, macOS v 12.6 (21G115), MacBook Pro 14 inch with M1 Pro

Matching spec and still unable to repro, will have to keep an eye. Thanks for the report!

**Comment by jahirfiquitiva** [comment] 2022-10-20 15:17
thanks @andy-hook 🙌

**Closed** 2024-02-21 14:46 UTC
