### ISSUE TITLE
Migrate width transition to scale transition in Progress example

### ISSUE THREAD

**Issue by mkv27** [radix-ui/website#216] opened 2021-07-28 22:38 UTC
### Overview

Better transition performance in https://www.radix-ui.com/docs/primitives/components/progress example

### Examples in other libraries

https://developers.google.com/web/updates/2017/03/performant-expand-and-collapse#bad_animating_width_and_height_on_a_container_element

### Who does this impact? Who is this for?

Help all radix users maintain good performance in their projects

**Comment by benoitgrelard** [comment] 2021-07-29 12:57
duplicate of #215

**Closed by benoitgrelard** 2021-07-29 12:57 UTC

**Comment by peduarte** [comment] 2021-07-29 12:59
im so confused 😅

**Comment by benoitgrelard** [comment] 2021-07-29 13:08
Haha, @mkv27 had already realised that he created this one in the wrong repo so he closed it and opened another one on the website repo. Then you saw this one and thought you'd transfer it over and reopen…
